# Introduction

## Imagerie visuelle et aphantasie

L'imagerie visuelle, parfois désignée poétiquement comme le fait de "voir dans les yeux de l'esprit", désigne l'expérience visuelle quasi-perceptive d'images mentales en l'absence du stimulus externe correspondant [@monzelAphantasiaDysikonesiaAnauralia2022; @pearsonHumanImaginationCognitive2019]. L'imagerie visuelle est considérée par la plupart des gens comme un élément central de leur vie mentale quotidienne, dans la mémorisation et la récupération d'informations sur des lieux, des objets ou des personnes connus, dans le vagabondage mental et la rêverie, voire plus généralement dans la créativité [@zemanLivesImageryCongenital2015]. Il a été démontré qu'elle joue un rôle prépondérant dans de nombreux processus cognitifs, tels que la mémoire autobiographique, la mémoire épisodique et la prospection d’évènements futurs [@greenbergRoleVisualImagery2014], la mémoire de travail visuelle [@pearsonHumanImaginationCognitive2019].

Cependant, il a été démontré qu'il pouvait exister une grande variabilité interindividuelle dans l'imagerie visuelle, et que certaines personnes pouvaient même en être totalement dépourvues. L'une des toutes premières études sur l'imagerie visuelle, une enquête menée par Sir Francis Galton en 1880, a apporté les premiers témoignages de la grande variété de la capacité des gens à produire des images mentales. Son "enquête sur la table du petit-déjeuner" invitait les participants à visualiser leur table du matin et à évaluer "l'illumination, la définition et la coloration" des images mentales qu'ils en avaient. À son grand étonnement, il a découvert que certaines personnes interrogées, parmi lesquelles beaucoup de ses collègues, dans ses termes des "hommes de science", ont protesté que l'imagerie mentale leur était inconnue - tout comme les daltoniens ne pouvaient pas concevoir la nature de la couleur, ces personnes ne pouvaient pas concevoir la nature de l'imagerie mentale [@galtonSTATISTICSMENTALIMAGERY1880].     

Il est intéressant de noter que, bien qu'il y ait eu une résurgence des recherches et des débats sur l'imagerie mentale à la fin du siècle qui a suivi (e.g. @kosslynCognitiveNeuroscienceMental1995; @pylyshynMentalImagerySearch2002; @reisbergIntuitionsIntrospectionsImagery2002), cette condition d'"imagination aveugle" n'a pas suscité beaucoup d'attention. Une exception notable est Faw [-@fawConflictingIntuitionsMay2009], qui a soulevé le fait que les théories des chercheurs sur l'imagerie pourraient être fortement biaisées par leur propre expérience subjective de celle-ci. Il a indiqué que les "non-visualiseurs", ignorés par la recherche jusqu'à présent, pourraient représenter 2 à 3 % des personnes, selon son enquête (*N* = 2500). En 2010, Zeman et al. ont rapporté le cas d'un patient qui a perdu la capacité de produire des images mentales après avoir subi une intervention chirurgicale [@zemanLossImageryPhenomenology2010]. L'article a attiré l'attention du public après un reportage dans le magazine *Discovery* [@zimmerBrainLookDeep2010] : bien qu'il s'agisse apparemment d'imagination aveugle "acquise", l'article a conduit de nombreuses personnes à se reconnaître dans cette condition et à contacter l'équipe pour témoigner de leur expérience, avec la différence importante qu'elles avaient toujours eu cette absence d'imagerie. En décrivant leurs cas, Zeman et al. [-@zemanLivesImageryCongenital2015] ont créé le terme "*aphantasie*" pour décrire l'absence d'imagerie mentale.    

L'aphantasie, en tant que terme et phénomène, a attiré l'attention des médias et a entraîné une augmentation importante du nombre de personnes signalant leur cas d'imagerie extrême [@monzelAphantasiaDysikonesiaAnauralia2022]. Les études à grande échelle sur les extrêmes de l'imagerie visuelle suggèrent une prévalence de 2-4% d'aphantasie dans la population générale (@dancePrevalenceAphantasiaImagery2022 : *N* = 1004 ; @dawesCognitiveProfileMultisensory2020 : *N* = 715 ; @fawConflictingIntuitionsMay2009 : *N* = 2500 ; @palermoCongenitalLackExtraordinary2022 : *N* = 490 ; @takahashiDiversityAphantasiaRevealed2022: *N* = 2885 ; @zemanPhantasiaPsychologicalSignificance2020) avec de nombreuses variations (entre 0,5 et 11%) selon les seuils choisis pour caractériser l'affection. L'étude de l'aphantasie est récente, et bien qu'il n'existe pas actuellement de " profil " clairement défini des individus aphantasiques, la recherche a lentement assemblé plusieurs caractéristiques associées à cette condition. 

## Les corrélats de l'aphantasie

Depuis 2015, le nouveau champ scientifique de l'aphantasie a construit un corpus de divers corrélats cognitifs, comportementaux et physiologiques de l'aphantasie. Communément, l'aphantasie est évaluée dans des études à grande échelle en utilisant des auto-rapports qualitatifs et le questionnaire Vividness of Visual Imagery [@marksVividnessVisualImagery1973], même si le seuil VVIQ choisi pour caractériser les personnes ayant une faible imagerie varie selon les études (entre 16 ~ 30). En utilisant les questionnaires comme point de départ, plusieurs études expérimentales ont été en mesure de corréler une faible imagerie visuelle avec des caractéristiques distinctes. 

### Corrélats cognitifs

La plupart des études à grande échelle existantes sur l'aphantasie ont porté sur les capacités de mémoire des aphantasiques, et ont montré des corrélations entre leur faible imagerie et des déficiences en mémoire autobiographique et épisodique [@dawesCognitiveProfileMultisensory2020; @miltonBehavioralNeuralSignatures2021; @zemanPhantasiaPsychologicalSignificance2020]. Les aphantasiques, lorsqu'on leur demande d'évaluer leur mémoire autobiographique, l'évaluent le plus souvent plus bas que les témoins [@zemanLivesImageryCongenital2015; @zemanPhantasiaPsychologicalSignificance2020]. L'un de ces rapports subjectifs a fait émerger la possibilité d'une association de l'aphantasie avec les syndromes de mémoire autobiographique sévèrement déficiente [@watkinsPhantasiaSeverelyDeficient2018]. En accord avec les auto-rapports et les données neuropsychologiques sur la mémoire épisodique, Dawes et al. [-@dawesInnerVisionsMind2022] ont démontré, à l'aide de l'Autobiographical Interview, une mesure comportementale de la spécificité et de la richesse des détails épisodiques (combinant donc des évaluations subjectives et objectives) que l'aphantasie était également associée à une réduction des détails épisodiques pour les évènements passés et futurs. Leurs résultats sont également en accord avec ceux de Milton et al. [-@miltonBehavioralNeuralSignatures2021] qui ont mis en évidence une réduction de l'"imagination" temporelle et atemporelle, à savoir la capacité à simuler des évènements fictifs. L'aphantasie a également été associée à la prosopagnosie - la difficulté à reconnaître les visages [@dawesCognitiveProfileMultisensory2020; @miltonBehavioralNeuralSignatures2021; @palermoCongenitalLackExtraordinary2022; @zemanPhantasiaPsychologicalSignificance2020], et à des rêves nocturnes et diurnes qualitativement appauvris [@dawesCognitiveProfileMultisensory2020; @zemanPhantasiaPsychologicalSignificance2020].

### Corrélats comportementaux et physiologiques

Comme nous l'avons mentionné, la plupart des études sur l'aphantasie se sont appuyées sur des évaluations subjectives, des questionnaires et des rapports personnels pour identifier et évaluer la condition et l'imagerie visuelle. Bien que les phénomènes subjectifs rapportés par les aphantasiques montrent une cohérence remarquable, les rapports à la première personne et l'introspection restent faillibles [@miltonBehavioralNeuralSignatures2021; @zemanPhantasiaPsychologicalSignificance2020]. Les différences dans les jugements d'imagerie visuelle pourraient être liées à une mauvaise métacognition, résultant en une incapacité des aphantasiques à percevoir consciemment leur imagerie potentiellement effective. Pour surmonter cette limitation, de nouvelles méthodes de mesure de l'imagerie visuelle et de son absence ont été développées afin de trianguler ces auto-rapports subjectifs avec des marqueurs comportementaux et physiologiques objectifs. Ainsi, il a été démontré que les personnes atteintes d'aphantasie ne présentent pas d'amorçage par l'imagerie visuelle par rapport aux témoins en utilisant le paradigme de rivalité binoculaire basé sur les sens [@keoghAttentionDrivenPhantom2020; @keoghBlindMindNo2018] ; elles se souviennent de moins d'objets et de couleurs que les témoins à partir de scènes étudiées [@bainbridgeQuantifyingAphantasiaDrawing2021] ; ils ont montré moins de sensibilité sensorielle dans une tâche d'éblouissement de motifs visuels, ce qui suggère que l'imagerie sensorielle et la sensibilité sensorielle sont liées [@danceLessSensoryOverwhelm2022; @danceWhatLinkMental2021] ; ils n'ont pas montré de réponse de conductivité cutanée à l'imagerie émotionnelle lors de la lecture de scénarios effrayants (Wicken et al., 2019) ; et enfin, ils n'ont pas montré de réponse pupillaire à des formes claires ou sombres imaginées [@lachlanPupillaryLightResponse2022]. Ces deux derniers paradigmes en particulier ont établi les premiers indices physiologiques de la force de l'imagerie sensorielle et phénoménologique, et les premières validations physiologiques de l'aphantasie. L'investigation du phénomène de l'imagerie visuelle par ces méthodes objectives a permis de rassembler des preuves solides en faveur de la conception de l'aphantasie comme une véritable absence (ou une réduction sévère) de l'imagerie visuelle plutôt que comme un déficit métacognitif.

### L'aphantasie est elle un trouble ?

L'aphantasie a été associée dans la littérature récente à une série de déficiences et de déficits, et est donc souvent logiquement désignée comme un handicap ou un trouble (e.g. @blomkvistAphantasiaSearchTheory2022; @fox-muratonWorldImaginationConsequences2021) ; certaines revues vont jusqu'à caractériser la condition comme un ensemble de déficiences résultant d'un dysfonctionnement d'un système cognitif [@blomkvistAphantasiaSearchTheory2022]. Bien que ce point de vue puisse être justifié d'une certaine manière si l'on considère que les déficiences de l'imagerie mentale peuvent survenir à la suite de lésions cérébrales, d'opérations chirurgicales ou de troubles psychiatriques - une condition appelée "aphantasie acquise" [@bartolomeoAssessingCausalRole2020; @cavedon-taylorPredictiveProcessingPerception2021; @farahCaseStudyMental1988; @spagnaChapterVisualMental2022; @zagoCharcotBernardCase2011; @zemanLossImageryPhenomenology2010], on peut trouver à redire sur plusieurs observations dans l'aphantasie congénitale (c'est-à-dire à vie). Des preuves empiriques provenant de plusieurs études soulignent que les aphantasiques pourraient n'avoir aucune différence de performance dans divers types de tâches présumées nécessiter une imagerie visuelle.     

Tout d'abord, en contraste frappant avec les résultats suggestifs sur la mémoire épisodique, les aphantasiques ont des performances aussi précises que les témoins dans plusieurs paradigmes de mémoire de travail visuelle en laboratoire et en clinique [@keoghVisualWorkingMemory2021; @knightMemoryImageryNo2022] ; ils ont également les mêmes performances dans les tâches de mémoire clinique évaluant le rappel antérograde [@miltonBehavioralNeuralSignatures2021] et la mémoire de reconnaissance pour le matériel verbal et visuel [@bainbridgeQuantifyingAphantasiaDrawing2021; @miltonBehavioralNeuralSignatures2021] ; ils ne présentent pas de différences significatives dans les tâches de mémoire sémantique [@dawesCognitiveProfileMultisensory2020; @miltonBehavioralNeuralSignatures2021] ; de même, ils ne présentent pas de déficience de la mémoire déclarative générale ou visuelle dans une batterie de tests neuropsychologiques [@pounderOnlyMinimalDifferences2022]. Keogh et al. [-@keoghVisualWorkingMemory2021] soulignent également dans leur étude le fait que les performances des aphantasiques dans les tâches d'imagerie visuelle peuvent s'appuyer sur des stratégies différentes, sur la base des différences notables entre leurs stratégies rapportées, et corroborées par une absence d'effet d'orientation dans leurs réponses, supposé se produire en raison du recrutement sensoriel. Zeman et al. [-@zemanPhantasiaPsychologicalSignificance2020] font état de rapport similaires d'aphantasiques utilisant des stratégies alternatives^[Il est à noter que l'utilisation de la terminologie "*stratégie alternative*" et "*compensation*" vient du fait de la majorité des personnes "non-aphantasiques" : elle souligne aussi la difficulté pour quelqu'un disposant d'imagerie visuelle à ne pas voir son absence comme un trouble.] pour résoudre une tâche de comptage du nombre de fenêtres chez soi : ils expliquaient avoir recours à l'imagerie spatiale, à l'imagerie kinesthésique (i.e. de mouvement), et aux connaissances amodales.         

Pris ensemble, ces résultats suggèrent que les aphantasiques ne présentent pas de problèmes de mémoire de travail, de reconnaissance ou de mémoire déclarative (générale ou visuelle) qui pourraient s'avérer affecter leur vie quotidienne. Ils reflètent également le fait que ces performances pourraient s'appuyer sur des stratégies alternatives non visuelles tout aussi adaptées pour résoudre des problèmes supposés auparavant nécessiter une imagerie visuelle. Ceci plaide pour considérer que les aphantasiques utilisent des approches alternatives qui pourraient ne pas être uniquement de la compensation, mais un tout autre " mode de fonctionnement humain du traitement de l'information " [@zemanPhantasiaPsychologicalSignificance2020] : si nous adhérons à ce point de vue, les spécificités des différences entre ces modes restent encore à déterminer. 

### Expériences de vie et "styles cognitifs"

En accord avec le fait que leur vie quotidienne ne semble pas être affectée par leur état, les aphantasiques sont le plus souvent inconscients de leur celui-ci, qui est de la même manière invisible pour les gens, puisqu'ils ne vivent apparemment pas différemment de n'importe qui d'autre [@kendleAphantasiaExperiencesPerceptions2017; @zemanLivesImageryCongenital2015]. Bien qu'il n'existe pas, à ce jour, d'étude systématique du profil démographique des aphantasiques, les résultats préliminaires d'une étude récente [@zemanPhantasiaPsychologicalSignificance2020] apportent un éclairage sur les préférences professionnelles potentielles des personnes dotées d'imageries extrêmes. En effet, les données des questionnaires de milliers de participants sur l'imagerie visuelle ont révélé que les extrêmes de ce spectre présentaient des associations comportementales et psychologiques distinctes, y compris des préférences professionnelles : alors que les personnes présentant une imagerie visuelle extrêmement élevée (appelées "hyperphantasiques") avaient tendance à travailler dans des professions traditionnellement considérées comme "créatives" (à savoir les arts, le design, le divertissement et la communication), les aphantasiques étaient plus susceptibles de travailler dans l'informatique, les mathématiques et les sciences [@crowderDifferencesSpatialVisualization2018; @zemanPhantasiaPsychologicalSignificance2020]. Ces résultats apportent un autre argument, d'un point de vue comportemental plus large, vers l'idée d'une tension entre deux "styles cognitifs" [@kozhevnikovSpatialObjectVisualizers2005], et une vision de l'aphantasie et de l'hyperphantasie comme des conditions équilibrées, avec des avantages et des inconvénients [@zemanPhantasiaPsychologicalSignificance2020].       

Bien que les affirmations initiales de Galton selon lesquelles les "hommes de science" manquaient d'imagerie mentale aient été contestées depuis - et qu'il ait été démontré qu'il s'agissait d'une généralisation excessive de son observation de quelques répondants particulièrement inhabituels parmi ses collègues scientifiques [@brewerScientistsAreNot2006] - son récit reste intéressant en suivant l'inférence inverse : Si les aphantasiques sont effectivement très peu nombreux, comme l'ont montré des données plus récentes, ont-ils vraiment tendance à se tourner vers les domaines scientifiques ? Les premiers résultats concernant les aphantasiques semblent corroborer cette intuition. Pourtant, quelles bases cognitives pourraient sous-tendre ces différentes stratégies mentales des aphantasiques et ces apparentes affinités intellectuelles ? Quelle est la nature des différents "modes" supposés de traitement de l'information visuelle ?

## Stratégies et mécanismes de compensation possibles dans l'aphantasie

### Opposition entre le visuel et l'abstrait

Galton expliquait son hypothèse sur les scientifiques par le potentiel antagonisme entre la visualisation d'images mentales et la pensée abstraite et holistique. Il constatait cependant que ses collègues aphantasiques^[L'appellation est anachronique mais utilisée à des fins de clarté.] pouvaient tout de même donner des descriptions précises de scènes visuelles. Il formulait déjà l'hypothèse d'une compensation par d'autres modes de conception, notamment des modes de pensées liés à l'imagerie motrice (la représentation mentale du mouvement et de la sensation de bouger) [@galtonSTATISTICSMENTALIMAGERY1880]. Dans des études sur le raisonnement et la visualisation mentale, Knauff et Johnson-Laird [-@knauffVisualImageryCan2002] ont montré que l'imagerie visuelle pouvait ralentir le processus de raisonnement, contrairement à l'imagerie visuospatiale, spatiale ou à la conceptualisation amodale.

### Stratégies verbales, sémantiques et abstraites

Zeman élabore aussi sur la compensation en émettant des hypothèses sur le développement de stratégies alternatives par les domaines verbaux, abstraits ou logiques, et pointe vers l'idée d'un traitement de l'information préférentiellement sémantique et factuel chez les aphantasiques [@zemanLivesImageryCongenital2015; @zemanPhantasiaPsychologicalSignificance2020]. Junichi et Jiro [-@junichiPreliminarySinglecaseStudy2020] ont étudié le cas d'un aphantasique par des questionnaires d'auto-évaluation. Le participant présentait des capacités d'imagerie auditive préservées et rapportait avoir recours à des stratégies verbales en réponse à des situations supposées comme nécessitant de l'imagerie visuelle, corroborant les observations de Zeman et al [-@zemanPhantasiaPsychologicalSignificance2020]. Ganczarek et al. [-@ganczarekRememberThingsCan2020] ont étudié le cas d'une aphantasique présentant des résultats faibles à la composante "imagerie visuelle-objet" (correspondant à ce qui est couramment appelé "imagerie visuelle") du questionnaire OSIVQ, mais des scores spatiaux et verbaux dans la norme, témoignant d'une préférence pour le raisonnement spatial et verbal. Elle ne présentait pas de troubles de la mémoire de travail visuospatiale. Son QI total était élevé (128), avec une différence marquée entre le QI verbal et le QI performance au profit du verbal (138 et 114). Milton et al. [-@miltonBehavioralNeuralSignatures2021] soulignent aussi ce résultat dans leur étude, les participants aphantasiques présentant un QI plus élevé que les participants hyperphantasiques. Une hypothèse liée aux fonctionnements alternatifs pourrait concerner les fonctions exécutives, notamment la flexibilité mentale (capacité de passer d'une tâche cognitive à une autre) : les aphantasiques devant utiliser un plus grand panel de stratégies pour traiter des tâches mentales visuelles, ils pourraient donc présenter des fonctions exécutives de plus haut niveau que la moyenne.   
Suggate et Lenhard [-@suggateMentalImagerySkill2022] ont montré qu'une mesure objective de l'imagerie mentale (l'*Imagery Comparison Task*) était un prédicteur significatif des performances de compréhension en lecture, alors que les auto-évaluations subjectives (le *Plymouth Sensory Imagery Questionnaire* et le *Spontaneous Use of Imagery Survey*) ne montraient pas de lien. Ces résultats montrent donc pour la première fois que les processus d'imagerie mentale sont intrinsèquement liés aux performances en lecture. Cette étude souligne aussi l'intérêt de l'utilisation d'une tâche écologique impliquant les images mentales par rapport aux traditionnels questionnaires.

### Imagerie visuelle-objet et visuospatiale

Autre hypothèse reposerait sur la distinction fondamentale dans l'imagerie visuelle entre deux composantes, l'imagerie *visuelle-objet* (c'est-à-dire la représentation mentale des caractéristiques visuelles d'un objet telles que la forme, la luminosité ou la couleur) et l'imagerie *visuelle-spatiale* (ou visuospatiale - i.e. la représentation mentale des emplacements spatiaux et des relations entre les parties d'un objet). Un résultat expérimental cohérent dans toutes les études récentes sur l'aphantasie est l'imagerie spatiale préservée des aphantasiques, par opposition à leur imagerie d'objet altérée. En utilisant l'OSIQ, plusieurs études ont montré qu'il n'y avait pas de différence significative entre les aphantasiques et les témoins sur les items d'imagerie spatiale [@bainbridgeQuantifyingAphantasiaDrawing2021; @dawesCognitiveProfileMultisensory2020; @keoghBlindMindNo2018; @miltonBehavioralNeuralSignatures2021; @zemanPhantasiaPsychologicalSignificance2020]. Les aphantasiques ont obtenu des résultats précis au test des mannequins et aux tâches de rotation mentale, impliquant la rotation mentale d'avatars ou d'objets [@crowderDifferencesSpatialVisualization2018; @miltonBehavioralNeuralSignatures2021; @pounderOnlyMinimalDifferences2022] - bien que Pounder et al. [-@pounderOnlyMinimalDifferences2022] aient signalé des temps de réponse plus lents pour les aphantasiques à très faible imagerie. Dans la même lignée, Bainbridge et al. [-@bainbridgeQuantifyingAphantasiaDrawing2021] ont observé que, lorsqu'on leur demande de dessiner de mémoire une scène vue précédemment, les aphantasiques se souviennent de beaucoup moins d'objets et de façon moins détaillée que les témoins, mais avec des tailles, des emplacements et une organisation corrects, voire plus précis. Ensemble, ces résultats suggèrent que les "aphantasiques" actuellement les plus étudiés sont en fait des *aphantasiques "objets"*, avec une imagerie visuospatiale intacte.       

Des résultats intéressants dans la littérature sur l'imagerie spatiale semblent faire écho aux premiers résultats de Zeman et al. [-@zemanPhantasiaPsychologicalSignificance2020] sur les préférences professionnelles des aphantasiques (objet). Les hautes performances dans les tests de visualisation spatiale sont corrélées aux performances professionnelles et académiques dans divers domaines des STEM (*Science, Technology, Engineering and Mathematics*), notamment la physique, la chimie organique, la géologie, les mathématiques, ainsi que la chirurgie, l'architecture et le raisonnement mécanique [@colemanSpatialPerceptionSkills1998; @hegartyIndividualDifferencesSpatial2005; @keehnerSpatialAbilityExperience2004; @kozhevnikovSpatialVisualizationPhysics2007; @orionRelationshipEarthScienceEducation1997; @waiSpatialAbilitySTEM2009]. D'autres études ont mis en évidence que la réussite dans les STEM reposait sur des capacités fondamentales d'imagerie spatiale telles que l'imagination de structures schématiques ou l'exécution de transformations spatiales mentales [@kozhevnikovSpatialVisualizationPhysics2007; @waiSpatialAbilitySTEM2009]. Ces considérations jettent également un nouvel éclairage sur les observations et les intuitions de Galton [-@galtonSTATISTICSMENTALIMAGERY1880] concernant les scientifiques. Blajenkova et al. [@blajenkovaObjectSpatialImagery2006] ont proposé une explication avec le clivage objet-spatial : les scientifiques ne seraient pas complètement déficients en imagerie visuelle générale, comme le suggérait Galton, mais seraient seulement sélectivement déficients en imagerie visuelle-objet.       

En outre, les recherches sur les différences individuelles en matière d'imagerie ont démontré que les scientifiques et les ingénieurs ont tendance à être des imageurs spatiaux tandis que les artistes visuels ont tendance à être des imageurs objet [@blajenkovaObjectSpatialImagery2006; @blazhenkovaNewObjectspatialverbalCognitive2009; @blazhenkovaVisualobjectAbilityNew2010; @kozhevnikovSpatialObjectVisualizers2005; @kozhevnikovTradeoffObjectSpatial2010]. Ces études ont non seulement montré, par le biais de rapports subjectifs, que les artistes et les scientifiques différaient en termes d'imagerie, mais elles ont également mis en évidence des différences de performance : les artistes ont obtenu de meilleurs résultats dans les tâches nécessitant la visualisation d'objets (par exemple, la création de représentations d'images et de couleurs, l'identification d'objets dégradés) ; tandis que les visualiseurs spatiaux et les scientifiques ont obtenu de meilleurs résultats dans les tâches nécessitant une visualisation spatiale (par exemple, la rotation mentale, le pliage de papier, la recherche d'un emplacement). Enfin, Kozhevnikov et al. [@kozhevnikovCreativityVisualizationAbilities2013] ont constaté que les évaluations de l'imagerie de visualisation d'objets par rapport à celle de visualisation spatiale étaient respectivement et sélectivement associées aux évaluations de créativité artistique par rapport à celle de créativité scientifique. 

## Objectifs

Les images mentales sont impliquées dans de nombreux processus cognitifs, comme la mémoire autobiographique, l’imagination du futur, la mémoire de travail visuelle, la compréhension du langage, le raisonnement moral, ou encore les rêves. A l’inverse on peut concevoir que certaines tâches soient gênées par la création d’images mentales, par exemple des tâches qui nécessitent des représentations plus abstraites, comme la catégorisation, le raisonnement analogique ou la visualisation spatiale. Sur cette base, l'étude des personnes dépourvues d'imagerie mentale visuelle présente un intérêt particulier pour la compréhension des liens entre différentes fonctions cognitives.      
L'objectif de cette étude exploratoire sera donc d'identifier des premiers aspects d'un profil cognitif cohérent des aphantasiques, et plus largement de profils corrélés aux variations dans l'imagerie mentale visuelle et dans la conceptualisation abstraite. Nous mesurerons  les performances de personnes aphantasiques et non-aphantasiques dans différents domaines cognitifs via une batterie de questionnaires, de tests neuropsychologiques et de tâches comportementales liés à l'imagerie visuelle, visuospatiale, au raisonnement verbal et non-verbal, à la mémoire de travail verbale et visuospatiale, ainsi qu'à la flexibilité mentale.        

Si les images mentales sont un frein au raisonnement abstrait, nous pouvons faire l'hypothèse que les personnes aphantasiques soient meilleures dans des tâches de catégorisation, de conceptualisation et de raisonnement. Les performances à ces tâches devraient également être négativement corrélées aux scores d’imagerie mentale (VVIQ, OSIQ-Objet). En conséquence, si les tâches de raisonnement sont liées à l'imagerie spatiale, nous pourrions émettre l'hypothèse que l'imagerie visuelle-objet soit négativement corrélée à certaines composantes de l'imagerie spatiale ou visuo-spatiale. Nous mettrons également en relation leur fonctionnement cognitif avec des tâches nécessitant de l’imagerie mentale mais n'étant pas nécessairement échouées par les aphantasiques. Dans quelle mesure performeraient-ils à une tâche écologique de compréhension de texte censée solliciter la création d’images mentales  ? Les performances à cette tâche et à celles de raisonnement sont elles liées à de meilleures fontions exécutives ? L'aphantasie est elle associée à un fonctionnement exécutif et intellectuel général plus élevé ?        

Cette étude sera donc exploratoire et nécessitera des outils spécifiques pour analyser nos groupes de participants sans *a priori* et identifier les facteurs les plus significatifs dans leur profils cognitifs. Ce dossier aura donc pour objectif de présenter un plan expérimental et analytique pour répondre à cette visée, et présenter une simulation de données et de leur analyse pour illustrer ce propos. Nous introduirons une méthode d'Analyse Factorielle Multiple et des graphes pour identifier les facteurs cognitifs les plus déterminants dans nos données et réduire nos variables, et utiliserons un algorithme de partition partition non-supervisée par la méthode des *k-means* pour étudier la répartion de nos participants dans des groupes pertinents avec leurs profils cognitifs.



<!-- Mon manuscrit initial se concentre sur le parallèle entre imagerie visuelle et visuospatiale : ci-dessous les parties retirées

## La disctinction entre imagerie visuelle-objet et visuospatiale

Une hypothèse est que cette dualité reposerait sur la distinction fondamentale, dans l'imagerie visuelle, entre deux composantes, l'imagerie visuelle-objet (c'est-à-dire la représentation mentale des caractéristiques visuelles d'un objet telles que la forme, la luminosité ou la couleur) et l'imagerie visuelle-spatiale (c'est-à-dire la représentation mentale des emplacements spatiaux et des relations entre les parties d'un objet).

### Voies ventrales et dorsales dans la perception et l'imagerie visuelle

La distinction entre le traitement des objets et le traitement spatial a d'abord été introduite pour la perception visuelle [@mishkinContributionStriateInputs1982], puis proposée pour la mémoire de travail visuelle [@dellasalaPatternSpanTool1999; @salwayVisuospatialWorkingMemory1995]. Il a été démontré que le traitement visuel de plus haut niveau est divisé en deux voies distinctes sur le plan fonctionnel et anatomique : la voie ventrale, qui va du lobe occipital au lobe temporal inférieur et qui traite les propriétés des objets (couleurs, forme, luminosité), et la voie dorsale, qui va du lobe occipital au lobe pariétal postérieur et qui traite les propriétés spatiales. Sur la base de données comportementales, neuropsychologiques et de neuroimagerie [@blajenkovaObjectspatialImageryNew2006; @bocciaPennyYourThoughts2015; @kozhevnikovRevisingVisualizerVerbalizerDimension2002; @kozhevnikovSpatialObjectVisualizers2005; @mortonImageTransformationDissociated1995; @palermoCongenitalLackExtraordinary2022], une distinction objet-spatial similaire a été suggérée pour l'imagerie visuelle. Ce contexte théorique a conduit au développement et à la validation d'un questionnaire permettant d'évaluer ces deux aspects de l'imagerie visuelle, l'Object and Spatial Imagery Questionnaire (OSIQ : @blajenkovaObjectspatialImageryNew2006).

### L'imagerie objet et spatiale chez les aphantasiques

Dans ce cadre, cette distinction entre imagerie objet et imagerie spatiale pourrait être centrale pour la compréhension de l'aphantasie : les cas étudiés jusqu'à présent sont-ils dépourvus d'imagerie visuelle objet, spatiale ou les deux ? Un résultat expérimental remarquablement cohérent dans toutes les études récentes sur l'aphantasie est l'imagerie spatiale préservée des aphantasiques, par opposition à leur imagerie d'objet altérée. En utilisant l'OSIQ, plusieurs études ont montré qu'il n'y avait pas de différence significative entre les aphantasiques et les témoins sur les items d'imagerie spatiale [@bainbridgeQuantifyingAphantasiaDrawing2021; @dawesCognitiveProfileMultisensory2020; @keoghBlindMindNo2018; @miltonBehavioralNeuralSignatures2021; @zemanPhantasiaPsychologicalSignificance2020]. Les aphantasiques ont obtenu des résultats précis au test des mannequins et aux tâches de rotation mentale, impliquant la rotation mentale d'avatars ou d'objets [@crowderDifferencesSpatialVisualization2018; @miltonBehavioralNeuralSignatures2021; @pounderOnlyMinimalDifferences2022] - bien que Pounder et al. [-@pounderOnlyMinimalDifferences2022] aient signalé des temps de réponse plus lents pour les aphantasiques à très faible imagerie. Zeman et al. [-@zemanPhantasiaPsychologicalSignificance2020] rapportent que, lorsqu'on leur demande d'imaginer et de compter les fenêtres de leur maison, les personnes ayant une imagerie élevée ou moyenne s'appuient systématiquement sur l'imagerie visuelle, tandis que les aphantasiques utilisent diverses autres stratégies : visualisation ou mémoire spatiale, imagerie alternative (kinesthésique, auditive, etc.), traitement sémantique ou " connaissances " amodales. De même, Bainbridge et al. [-@bainbridgeQuantifyingAphantasiaDrawing2021] ont observé que, lorsqu'on leur demande de dessiner de mémoire une scène vue précédemment, les aphantasiques se souviennent de beaucoup moins d'objets et de façon moins détaillée que les témoins, mais avec des tailles, des emplacements et une organisation corrects, voire plus précis. Ensemble, ces résultats suggèrent que les "aphantasiques" actuellement les plus étudiés sont en fait des aphantasiques "objets", avec une imagerie visuospatiale intacte.       

Ce phénomène pourrait être lié au fait que les individus aphantasiques ont été principalement identifiés à l'aide du VVIQ [@marksVividnessVisualImagery1973], qui est corrélé positivement avec l'échelle objet de l'OSIQ, mais pas avec l'échelle spatiale, ni avec les tâches d'imagerie spatiale [@blajenkovaObjectSpatialImagery2006; @blajenkovaObjectspatialImageryNew2006; @blazhenkovaTwoEyesBlind2019; @blazhenkovaVisualobjectAbilityNew2010]. Le VVIQ permettrait donc de détecter sélectivement les déficiences de l'imagerie visuelle des objets, mais pas de l'espace. À ce titre, Blazhenkova et Pechenkova [-@blazhenkovaTwoEyesBlind2019] ont émis l'hypothèse qu'il pourrait exister deux types d'imagerie extrême (potentiellement congénitale) : l'aphantasie des objets d'une part, et l'aphantasie spatiale d'autre part (et inversement, deux types d'hyperphantasie). Dans une étude récente examinant pour la première fois cette hypothèse de manière systématique, Palermo et al. [-@palermoCongenitalLackExtraordinary2022] ont rassemblé des preuves très prometteuses de l'existence d'aphantasies et d'hyperphantasies objectales et spatiales, en utilisant l'OSIQ et des questionnaires évaluant plusieurs compétences. Elles ont également montré que les deux sous-types d'aphantasie étaient associés à des modèles différents de difficultés cognitives : les aphantasiques "objet", comme nous l'avons vu précédemment, ont montré des difficultés à imaginer des objets et à reconnaître des visages, tandis que les aphantasiques "spatiaux" avaient des problèmes avec les tâches d'imagerie mentale visuospatiale et le sens de la direction - un modèle opposé de performances a été observé pour les deux types d'hyperphantasie. 

### Des styles cognitifs équilibrés entre imagerie objet et spatiale

Ces résultats sur l'imagerie d'objet et spatiale introduisent une deuxième dimension (spatiale) significative dans l'imagerie visuelle et la recherche sur l'aphantasie, qui semble afficher des modèles opposés à la composante (objet) qui a été distinguée dans les études précédentes : avoir ces deux axes permet d'envisager une possibilité pour le profil " équilibré " hypothétique de l'aphantasie, qui pourrait être basé sur un équilibre entre les méthodes de représentation mentale visuelle-objet et visuelle-spatiale.       

Des résultats intéressants dans la littérature sur l'imagerie spatiale semblent faire écho aux premiers résultats de Zeman et al. [-@zemanPhantasiaPsychologicalSignificance2020] sur les préférences professionnelles des aphantasiques (objet). Les hautes performances dans les tests de visualisation spatiale sont corrélées aux performances professionnelles et académiques dans divers domaines STEM, notamment la physique, la chimie organique, la géologie, les mathématiques, ainsi que la chirurgie, l'architecture et le raisonnement mécanique [@colemanSpatialPerceptionSkills1998; @hegartyIndividualDifferencesSpatial2005; @keehnerSpatialAbilityExperience2004; @kozhevnikovSpatialVisualizationPhysics2007; @orionRelationshipEarthScienceEducation1997; @waiSpatialAbilitySTEM2009]. D'autres études ont mis en évidence que la réussite dans les STEM reposait sur des capacités fondamentales d'imagerie spatiale telles que l'imagination de structures schématiques ou l'exécution de transformations spatiales mentales [@kozhevnikovSpatialVisualizationPhysics2007; @waiSpatialAbilitySTEM2009]. Ces considérations jettent également un nouvel éclairage sur les observations et les intuitions de Galton [-@galtonSTATISTICSMENTALIMAGERY1880] concernant les scientifiques. Blajenkova et al. [@blajenkovaObjectSpatialImagery2006] ont proposé une explication avec le clivage objet-spatial : les scientifiques ne seraient pas complètement déficients en imagerie visuelle générale, comme le suggérait Galton, mais seraient seulement sélectivement déficients en imagerie visuelle objet.       

En outre, les recherches sur les différences individuelles en matière d'imagerie ont démontré que les scientifiques et les ingénieurs ont tendance à être des imageurs spatiaux tandis que les artistes visuels ont tendance à être des imageurs objet [@blajenkovaObjectSpatialImagery2006; @blazhenkovaNewObjectspatialverbalCognitive2009; @blazhenkovaVisualobjectAbilityNew2010; @kozhevnikovSpatialObjectVisualizers2005; @kozhevnikovTradeoffObjectSpatial2010]. Ces études ont non seulement montré, par le biais de rapports subjectifs, que les artistes et les scientifiques différaient en termes d'imagerie, mais elles ont également mis en évidence des différences de performance : les artistes ont obtenu de meilleurs résultats dans les tâches nécessitant la visualisation d'objets (par exemple, la création de représentations d'images et de couleurs, l'identification d'objets dégradés) ; tandis que les visualiseurs spatiaux et les scientifiques ont obtenu de meilleurs résultats dans les tâches nécessitant une visualisation spatiale (par exemple, la rotation mentale, le pliage de papier, la recherche d'un emplacement). Enfin, Kozhevnikov et al. [@kozhevnikovCreativityVisualizationAbilities2013] ont constaté que les évaluations de l'imagerie de visualisation d'objets par rapport à celle de visualisation spatiale étaient respectivement et sélectivement associées aux évaluations de créativité artistique par rapport à celle de créativité scientifique. 

### Un "trade-off" entre imagerie objet et spatiale chez les aphantasiques ?

Une question ouverte reste celle du lien potentiel entre l'imagerie visuelle objet et spatiale, et plus particulièrement ici dans les cas d'aphantasie. Les voies ventrales et dorsales régissant ces deux aspects étant connues pour être fonctionnellement et anatomiquement différentes [@mishkinContributionStriateInputs1982], il a longtemps été considéré que les deux processus visuels objet et spatial étaient des composantes mutuellement indépendantes de la représentation et de l'imagerie [@farahCaseStudyMental1988; @mishkinContributionStriateInputs1982]. Néanmoins, Kozhevnikov et al. [@kozhevnikovTradeoffObjectSpatial2010] ont montré, sur cinq groupes d'âge différents et quatre groupes de spécialisation différents, que les artistes visuels avaient des capacités de visualisation d'objets supérieures à la moyenne mais des capacités de visualisation spatiale inférieures à la moyenne, tandis que les scientifiques présentaient le schéma inverse. Aucun des groupes professionnels (artistes, scientifiques, architectes ou spécialistes des sciences humaines) ne présentait à la fois des capacités de visualisation d'objets et des capacités de visualisation spatiale supérieures à la moyenne : il a donc été proposé qu'il pouvait y avoir un compromis entre les capacités de visualisation d'objets et les capacités de visualisation spatiale. Comme l'étude a montré que les scores d'imagerie globale (spatiale + objet) étaient relativement homogènes chez tous les participants, ce compromis impliquerait l'existence d'un "goulot d'étranglement" dans la quantité totale des capacités d'imagerie, qui nécessiterait leur affectation en fonction de l'activité de chacun. Par conséquent, on peut supposer qu'un tel compromis pourrait exister, dans le cas de l'aphantasie, entre les ressources objet et spatiales : les aphantasiques objet, les cas d'aphantasie les plus étudiés, pourraient potentiellement compenser cette imagerie objet réduite par une imagerie spatiale plus vive - une possibilité qui, jusqu'à présent, n'a pas été étudiée en profondeur en raison de l'accent mis sur la composante objet singulière de l'aphantasie.        

La dualité de l'imagerie visuelle entre l'objet et l'espace, l'existence proposée de formes spécifiques d'images extrêmes qui leur sont associées, et la distinction apparente des profils cognitifs entre les visualiseurs "objet" et les visualiseurs "espaces"spatiaux", soutiennent l'hypothèse que les aphantasies soient des conditions équilibrées. Elles pourraient avoir leurs propres avantages et inconvénients qui pourraient être répartis sur plusieurs dimensions : parmi lesquelles le traitement visuel-objet ou visuospatial, mais peut-être aussi le traitement verbal, en accord avec les modèles précédemment développés de styles cognitifs Objet-Spatial-Verbal [@blazhenkovaNewObjectspatialverbalCognitive2009], et comme l'ont supposé Zeman et al. [@zemanPhantasiaPsychologicalSignificance2020].
-->



