# Discussion

##### Une analyse exploratoire de l'imagerie mentale.

L'analyse dimensionnelle *data driven* peut mettre en évidence des liens entre des capacités cognitives à partir des données : elle pourrait permettre d'élucider les connections des différentes formes de l'imagerie entre elles et avec les compétences abstraites. Une analyse factorielle puis basée sur la théorie des graphes permettrait de lier les compétences individuelles en des réseaux fonctionnels cohérents dont la proximité ou la distance serait mise en évidence sans interférence des nos hypothèses.      
Dans cette simulation (dont la base est bien sûr teintée par toutes les connaissances et hypothèses *a priori*), l'Analyse Factorielle Multiple a permis de mettre en évidence trois composantes cognitives reflétées par nos facteurs: l'imagerie visuelle-objet, l'imagerie visuospatiale et le raisonnement. La pertinence analytique de la méthode est reflétée par la différence entre notre méthodologie de simulation et le résultat de l'AFM : nous avions initialement simulé douze variables et les avions liées linéairement à cinq facteurs latents, pondération qui était dépendante de nos présuppositions sur les facteurs en question. L'AFM en a extrait trois très pertinents, mais avait aussi identifié - dans un quatrième facteur moins impactant - la *mémoire de travail*. L'autre facteur que nous avions construit, la *flexibilité mentale*, a été évacué par l'analyse de facteurs car indiscernable des autres : nos variables étaient toutes plus corrélées à d'autres facteurs qu'à la flexibilité elle-même.
L'analyse successive en graphes par un *Gaussian Graphical Model* nous a permis d'observer les distances entre ces réseaux et leur liens réciproques. Sur la base d'une matrice corrélation entre les variables, elle a créé une analyse géométrique du plan de facteurs et une représentation de celui-ci. Cette représentation a montré sa capacité à révéler des liens entre variables mais aussi entre *réseaux*. Dans notre simulation nous avions par exemple créé intentionnellement^[Ces phénomènes n'existaient que de façon sous-jacente à nos coefficients du modèle factoriel, i.e. dans notre modèle d'*effets*.] deux phénomènes : une corrélation négative entre l'imagerie visuelle-objet d'un côté et l'imagerie spatiale et le raisonnement de l'autre, ainsi qu'une corrélation positive entre l'imagerie spatiale et le raisonnement. Ces deux phénomènes sont très bien retranscrits par le GGM, illustrant sa pertinence dans de tels modèles de données.

#### Vers la construction de profils cognitifs des aphantasies

Nos données - illustrant notre recrutement réel potentiel - étaient ici construites sur la base de deux sets de moyennes représentant deux groupes *supposés*, divisés selon un axe d'une seule dimension : le déficit (ou non) d'imagerie visuelle (objet). Cette étude a permis de démontrer la pertinence de l'intervention d'un algorithme de partition non-supervisée (*k-means*) pour redéfinir les groupes - si nécessaire - sur plusieurs dimensions en partant des données elles-mêmes et en s'affranchissant alors de nos connaissances préalables. Nous avons ici illustré une situation potentielle ou cette partition résulte en une recommandation de quatre groupes au lieu de deux. Du fait de la construction manuelle des données, ces groupes ont des caractéristiques exagérées. Néanmoins nous pouvons dégager le sens de la partition réalisée par l'algorithme (voir \autoref{radar}). Il existe deux groupes performants en raisonnement : un groupe performant à toutes les compétences (le cluster 2), composé majoritairement de non-aphantasiques - ceux-ci représentent les contrôles moyens et les aphantasiques "indiscernables". Il existe ensuite un groupe - le cluster 3 - très faible en imagerie objet mais encore davantage performant en raisonnement et imagerie spatiale, composé uniquement d'aphantasiques : il reflète les aphantasiques de "haut niveau" et illustre l'équilibre potentiellement avantageux des stratégies alternatives des aphantasiques^[Ce serait ici notre groupe d'"*aphantasiques scientifiques*".]. Le cluster 1 est mixte mais composé majoritairement de non-aphantasiques, et représente la moyenne basse des "compétences équilibrées" et des aphantasiques "indiscernables". Enfin le cluster 4, composé uniquement de non-aphantasiques, présente des moyennes très basses sauf en imagerie-objet, où il présente la moyenne la plus élevée : ce serait ici nos "hyperphantasiques".      

Le plan d'analyse et les simulations présentées ici ont permis de mettre en évidence l'intérêt dans un premier temps d'une étude dimensionnelle et exploratoire *data-driven* des compétences de l'imagerie et de l'abstraction, puis d'une analyse des données des participants partitionnées de façon non-supervisée. Nous avons ainsi établi avec ce dossier qu'un tel plan d'étude et d'analyse semble prometteur et fécond : ce plan sera potentiellement mis en application dès le deuxième trimestre 2023 dans l'étude réelle.